# Используем образ Node.js в качестве базового образа
FROM node:14.17.0-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы package.json и package-lock.json внутрь контейнера
COPY frontend/todo-vue-spa/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта внутрь контейнера
COPY frontend/todo-vue-spa/* .

# Запускаем фронтенд-приложение в режиме разработки
CMD ["npm", "run", "serve"]


